package com.example.chatapp

object Constants {
    const val PHONE_NUMBER = "phone"
    const val LOGIN_STATUS = "false"
    const val GROUP_NAME = ""
    const val SHARED_PREFS = "sharedPrefs"
    const val NOTIFICATION_TOKEN = "notificationToken"
    const val DEVICE_EMULATOR1 = "dFG-9uQdTg6kclTJd2pvZX:APA91bEeq7qAj7dVwyB5Ypig3mymbvMh4wDHEHJkXEuH_ky94S2fdgcsgCTau-KZrNRMnh0OanFWms_F0BVkXn7UbKiPwCkvh5iCR_sqA9tZi_3NdzC5LJt6ud6pp7ThrkpVLeNMCaor"
    const val DEVICE_EMULATOR2 = "dDivonp2S8ilbPzkFb8cDH:APA91bF0bK80qApTC51Y2EgTXLZCq_NFbaChkawbV9V4uwsT1LdnstXxNDfIjDvJrCoGxWZJxYwt7-r0CF_uUdNrMToX9uXTaoosBdQtmWVvdGZ0xAR01twYbwRHFP6iYtnP1-2Llf-b"
    const val NAME = "name"
    const val STATUS = "status"
    const val IMAGE_URL = "imageUrl"
    const val LANG_PREFS = "langPrefs"
    const val LANGUAGE = "language"
    const val DEVICE_EMULATOR3= "ceqRSudFTE-2rQPYl7VV2F:APA91bHYZi6Y2fwOP2AHiDoyPYwQUKqWnXEwfKADwQpZ9yZLUnmsbYhHrH_Jv1bE7U4-UC1IqZ1iJKb8SYVxWQJE_kgJjg_GOkvB17QrgyTZXbz2YcxRUabC3-ST96NA3bTPpUfV1SGU"
    const val SETTINGS = "settings"
    const val LANG = "lang"
    const val USER_NAME = "name"
    const val UID = "uid"
    const val GROUPS_NAME = "groupName"
    const val GROUP_CHATS = "GroupChats"
    const val GROUP_MESSAGES = "GroupMessages"
    const val CHATS = "chats"
    const val MESSAGES = "messages"
}